/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // AI Nexus custom tokens
        "bg-base": "#050508",
        "bg-surface": "#0a0a12",
        "bg-elevated": "#11111a",
        "accent-cyan": "#00d4ff",
        "accent-purple": "#8b5cf6",
        "accent-magenta": "#e879f9",
        "accent-green": "#22c55e",
        "accent-amber": "#f59e0b",
        "accent-red": "#ef4444",
        "text-primary": "#f1f5f9",
        "text-secondary": "#94a3b8",
        "text-muted": "#64748b",
        "text-inverse": "#0f172a",
        // Category node colors
        "cat-llms": "#3b82f6",
        "cat-agents": "#ef4444",
        "cat-codeai": "#22c55e",
        "cat-multimodal": "#a855f7",
        "cat-diffusion": "#ec4899",
        "cat-infra": "#06b6d4",
        "cat-frameworks": "#f59e0b",
        "cat-data": "#10b981",
        "cat-audio": "#f97316",
        "cat-robotics": "#6366f1",
        "cat-other": "#94a3b8",
        // Layer colors
        "layer-compute": "#0ea5e9",
        "layer-model": "#6366f1",
        "layer-framework": "#8b5cf6",
        "layer-agent": "#ec4899",
        "layer-tool": "#06b6d4",
        "layer-application": "#22c55e",
        "layer-data": "#10b981",
        "layer-interface": "#f59e0b",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Space Grotesk', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      spacing: {
        "space-1": "4px",
        "space-2": "8px",
        "space-3": "12px",
        "space-4": "16px",
        "space-6": "24px",
        "space-8": "32px",
        "space-12": "48px",
        "space-16": "64px",
        "space-24": "96px",
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        "radius-sm": "6px",
        "radius-md": "10px",
        "radius-lg": "16px",
        "radius-xl": "24px",
        "radius-full": "9999px",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "panel": "0 8px 32px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(255,255,255,0.05)",
        "card": "0 4px 16px rgba(0, 0, 0, 0.4), 0 0 0 1px rgba(255,255,255,0.03)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          from: { opacity: "0", transform: "translateX(100%)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.9)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "glow-pulse": {
          "0%, 100%": { boxShadow: "0 0 6px var(--glow-color, rgba(0,212,255,0.4))" },
          "50%": { boxShadow: "0 0 20px var(--glow-color, rgba(0,212,255,0.6)), 0 0 40px var(--glow-color, rgba(0,212,255,0.3))" },
        },
        "connection-flow": {
          from: { strokeDashoffset: "24" },
          to: { strokeDashoffset: "0" },
        },
        "node-float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-4px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "fade-in": "fade-in 400ms cubic-bezier(0.4, 0, 0.2, 1) forwards",
        "slide-up": "slide-up 500ms cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "slide-in-right": "slide-in-right 450ms cubic-bezier(0.85, 0, 0.15, 1) forwards",
        "scale-in": "scale-in 350ms cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "glow-pulse": "glow-pulse 2000ms ease-in-out infinite",
        "connection-flow": "connection-flow 3000ms linear infinite",
        "node-float": "node-float 8000ms ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
